name: Set up env and lint code

on:
  push:
    branches:
      - main

jobs:
  runs-on: ubuntu-20.04
  steps:
    - uses: actions/chekout@v4
    - uses: actions/setup-node@v4
      with: 
        node-version: '20'
      run: npm install
      run: npm run eslint
