name: Set up env and lint code

on:
  push:
    branches:
      - main

jobs:
  simple_pipeline:
    runs-on: self-hosted
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up
        uses: actions/setup-node@v4
        with: 
          node-version: '20'
      - name: Install dependencies
        run: npm install
      - name: Test style
        run: npm run eslint
