name: Set up env and lint code

on:
  push:
    branches:
      - main

jobs:
  simple_pipeline:
    runs-on: self-hosted #ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up
        uses: actions/setup-node@v4
        with: 
          node-version: '20'
      - name: Install dependencies
        run: npm install
      - name: Lint
        run: npm install eslint @eslint/js --save-dev
      - name: Build
        run: npm run build 
      - name: Test
        run: npm ci --save-dev @testing-library/react @testing-library/jest-dom && npm test --verbose 
