name: Set up env and lint code

on:
  push:
    branches:
      - main

jobs:
  pipeline:
    runs-on: self-hosted
    steps:
      - uses: actions/chekout@v4
        with:
          repository: ''
      - uses: actions/setup-node@v4
        with: 
          node-version: '20'
      - name: Install dependencies
        run: npm install
      - name: Test style
        run: npm run eslint
